### ISSUE TITLE
Zero results returned when GET request to ...api/transfer

### ISSUE THREAD

**Issue by s881628** [tronscan/tronscan-docker#1]
**Issue**
Submitting a GET request to _http://127.0.0.1:9000/api/transfer..._ Returns an empty object.
Submitting the exact same request to _https://api.tronscan.org/api/transfer..._ returns the correct object
Submitting any other request locally such as _http://127.0.0.1/api/block/latest_ returns the correct object

yaml configuration.  Changing node IPs doesn't make any difference
`version: '3.1'

services:
  tronscan:
    image: tronscan/api:latest
    ports:
      - "9000:9000"
    environment:
      NODE_FULL_IP: "52.56.56.149"
      NODE_FULL_PORT: "50051"
      NODE_SOLIDITY_IP: "34.250.140.143"
      NODE_SOLIDITY_PORT: "50051"
      ENABLE_SYNC: "false"
      ENABLE_NETWORK_SCANNER: "true"
      SECRET_KEY: "XXXXXXXXX"
  redis:
    image: redis:4.0
  pgsql:
    image: tronscan/db:latest`

There is nothing logged in the docker output window when this occurs however there are some other repeating errors.  Please see the example below.

`tronscan_1  | [error] i.g.i.ManagedChannelImpl - *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-59753 for target 35.231.191.216:50051 was not shutdown properly!!! ~*~*~*
tronscan_1  |     Make sure to call shutdown()/shutdownNow() and awaitTermination().
tronscan_1  | [error] i.g.i.ManagedChannelImpl - *~*~*~ Channel io.grpc.internal.ManagedChannelImpl-69370 for target 35.232.78.22:50051 was not shutdown properly!!! ~*~*~*
tronscan_1  |     Make sure to call shutdown()/shutdownNow() and awaitTermination().
tronscan_1  | java.lang.RuntimeException: ManagedChannel allocation site
tronscan_1  |   at io.grpc.internal.ManagedChannelImpl$ManagedChannelReference.<init>(ManagedChannelImpl.java:1185)
tronscan_1  |   at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:504)
tronscan_1  |   at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:369)
tronscan_1  |   at org.tronscan.grpc.GrpcPool.$anonfun$requestChannel$1(GrpcPool.scala:28)
tronscan_1  |   at scala.collection.MapLike.getOrElse(MapLike.scala:128)
tronscan_1  |   at scala.collection.MapLike.getOrElse$(MapLike.scala:126)
tronscan_1  |   at scala.collection.AbstractMap.getOrElse(Map.scala:59)
tronscan_1  |   at org.tronscan.grpc.GrpcPool.requestChannel(GrpcPool.scala:25)
tronscan_1  |   at org.tronscan.grpc.GrpcPool$$anonfun$receive$1.applyOrElse(GrpcPool.scala:44)
tronscan_1  |   at akka.actor.Actor.aroundReceive(Actor.scala:517)`

`PS C:\Users\neuromesh> Invoke-RestMethod -Method GET -uri http://127.0.0.1:9000/api/transfer?block=2065654

total data
----- ----
    0 {}  

PS C:\Users\neuromesh> Invoke-RestMethod -Method GET -uri https://api.tronscan.org/api/transfer?block=2065654

total data                                                                                                                                         
----- ----                                                                                                                                         
    0 {@{id=8346c32d-f925-4a2c-a35d-adb472ed28e8; transactionHash=057bde2129b051234d23b11b8ae0c63ac1944abd17619062eb280ef9006d16fd; block=206565...

PS C:\Users\s881628> Invoke-RestMethod -Method GET -uri http://127.0.0.1:9000/api/transfer?hash=057bde2129b051234d23b11b8ae0c63ac1944abd17619062eb280ef9006d16fd

total data
----- ----
    0 {}  

PS C:\Users\neuromesh> Invoke-RestMethod -Method GET -uri https://api.tronscan.org/api/transfer?hash=057bde2129b051234d23b11b8ae0c63ac1944abd17619062eb280ef9006d16fd

total data                                                                                                                                         
----- ----                                                                                                                                         
    0 {@{id=8346c32d-f925-4a2c-a35d-adb472ed28e8; transactionHash=057bde2129b051234d23b11b8ae0c63ac1944abd17619062eb280ef9006d16fd; block=206565...

PS C:\Users\neuromesh> Invoke-RestMethod -Method GET -uri http://127.0.0.1:9000/api/block/latest

number         : 2065864
hash           : 00000000001f85c826ac5a77f5896b8aba2a44496e03751e071c146d7d451a6e
size           : 1458
timestamp      : 1536103137000
txTrieRoot     : 22GGkX6fhyjUBo2d4QM38wEzN2BYsM2asrTaprzKYmfRpryDLj
parentHash     : 00000000001f85c75ce086dbc9095b968acf54eb9c4c8e9e52aa3eaa9e246f1a
witnessId      : 0
witnessAddress : TTcYhypP8m4phDhN6oRexz2174zAerjEWP
nrOfTrx        : 6
confirmed      : False`

**Comment by s881628** [comment]
Further to the above:
It appears that despite configuring docker-compose.yml to pull from tronscan/api:latest, the version that is running in my docker container is different to the one that is running at api.tronscan.org.
The swagger.json is completely different to what I am running.  For example, the online API offers "/api/block/sync" as where teh local docker version does not.  The entire web interface is different in terms of added options and ordering.

I am also starting to notice other issues calling some other endpoints such as _/api/grpc/solidity/listwitnesses_.  Calling it from the docker instance returns a 500 response with the exception code 796fac874

If the live API running a different unreleased version?
